### ISSUE TITLE
Package won't install on Windows

### ISSUE THREAD

**Issue by romans127** [nathanbuchar/atom-peacocks-in-space-syntax#1] opened 2015-08-22 00:51 UTC
I am using Windows 7 with version `1.0.7 of Atom` . 
I have tried to install the package several different ways and for some reason it won't install. 

Please advice.

**Comment by nathanbuchar** [comment] 2015-08-22 06:04
Hi @rwatts3, 

First off, thanks for your interest in the package!

There's nothing particularly advanced about this theme; it's just another ordinary syntax theme. So if other themes install just fine then it might be something really simple.

First, can you please provide more information? What does it do? Does it hang half-way through the install? Does it install fully but then doesn't show up in the syntax theme dropdown list? Do you get a red Atom error popup? If so, what does the error message say?

Some additional troubleshooting:

• Remember this is a syntax theme not a UI theme. Could you be looking in the UI theme dropdown instead of the syntax theme dropdown which would make you think it didn't install?
• Will other syntax themes install properly?
• Are you having any Internet connection issues?

**Comment by nathanbuchar** [comment] 2015-08-22 06:05
I'm on Mac OS X 10.11 Beta (15A262e),

I've uninstalled the theme and am trying to reinstall it (via Atom UI, not CLI) and it's hanging on the installing button animation. Other themes install just fine.

I'll keep looking into this!

**Update**: It took about a minute or two, but it did finally install. Can you give it about five minutes to install and let me know if it works? Thanks :)

**Comment by romans127** [comment] 2015-08-22 17:57
Hi. Actually. It installs perfectly on my Mac. Not in Windows. Yes I'm
certain I am following the install procedure correctly. When you click
install. It will hang and never install.

**Comment by nathanbuchar** [comment] 2015-08-22 20:35
As I don't have a Windows machine, this is difficult for me to test; However if anyone else coming to this thread is having the same issue, please add a :+1:

**Comment by nickelozz** [comment] 2016-07-27 17:58
Hi,

I'm trying to install this theme in atom under windows 7 SP1 and I get the following error:

```
Installing “peacocks-in-space-syntax@0.5.1” failed.Hide output…

> node-sass@3.8.0 install C:\Users\user\AppData\Local\Temp\apm-install-dir-116627-100400-kph38y\node_modules\peacocks-in-space-syntax\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\Users\user\AppData\Local\Temp\apm-install-dir-116627-100400-kph38y\node_modules\peacocks-in-space-syntax\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-11\binding.node

'C:\Users\user\.atom\.node-gyp\aliases.cmd' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\user\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\user\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\user\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\user\\.atom\\.apmrc" "install" "C:\\Users\\user\\AppData\\Local\\Temp\\d-116627-100400-bj3anv\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.8.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.8.0 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
```

Is there any way this issue can be solved? I'd really love to be able to use this theme!

**Comment by nathanbuchar** [comment] 2016-07-27 21:24
Hi @nickelozz,

This looks like it might be an issue with node sass. More interestingly: why am I requiring gulp-sass? I'll remove those dependencies tonight. In the mean time, you should be able to add the syntax theme to Atom's "packages" directory manually.

Simply download this repo and unzip it. Rename the folder to `peacocks-in-space-syntax`, drag that folder into `C:\Users\<user>\.atom\packages`, then restart Atom to make it available :)

**Comment by nathanbuchar** [comment] 2016-07-28 03:45
Should be fixed now.

**Comment by nickelozz** [comment] 2016-08-01 13:54
Hello @nathanbuchar I can confirm it's working now and is looking dandy!

Unless someone else notices any odd behavour I think it's safe to close this issue. Thanks a bunch!

**Closed as completed** 2016-08-01 18:39 UTC
Labels: bug, needs reproduction
